image: kuberlab/peakhealth:latest
imagePullPolicy: Always
serviceType: LoadBalancer

ingress:
    enabled: false
    hostname: peakhealth.local

    ## Ingress annotations
    ##
    # annotations:
    #   kubernetes.io/ingress.class: nginx

    ## Ingress TLS configuration
    ## Secrets must be manually created in the namespace
    ##
    # tls:
    #   - secretName: peakhealth.local-tls
    #     hosts:
    #       - peakhealth.local

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m

# Configure persistence storage
persistence:
  fromProvider: true
  size: 10Gi
  #storageClass: ""
  volume:
    awsElasticBlockStore:
      volumeID: <volume-id>
      fsType: ext4

# Configure Postgres
postgresql:
  image: postgres:9.5.4
  imagePullPolicy: IfNotPresent
# password: postgres
  nodeSelector:
    enabled: false
    labels:
      postgresql: postgresql

# Configure Clickhouse
clickhouse:
  image: yandex/clickhouse-server:latest
  imagePullPolicy: IfNotPresent
  server: clickhouse
  port: 9000
  user: default
# password: clickhouse
  db: metrics
  table: metrics
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 1
      memory: 4Gi

