apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    app: kuberlab
    component: postgresql
type: Opaque
data:
  {{- if .Values.password }}
  postgres-password:  {{ .Values.password | b64enc | quote }}
  {{- else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
