apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: kuberlab
    component: postgresql
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: kuberlab
    component: postgresql
